import * as vscode from "vscode";

export interface EnvPyFilter {
  type: "schema" | "table" | "glob" | "regex";
  pattern: string;
  mode: "include" | "exclude";
}

export interface EnvPyConfig {
  includeSchemas: boolean;
  filters: EnvPyFilter[];
}

/**
 * Utility for safely patching env.py files with context.configure options
 */
export class EnvPyEditor {
  /**
   * Creates a backup of env.py before making changes
   */
  static async createBackup(envPyUri: vscode.Uri): Promise<vscode.Uri> {
    const backupUri = vscode.Uri.file(envPyUri.fsPath + ".backup");
    const content = await vscode.workspace.fs.readFile(envPyUri);
    await vscode.workspace.fs.writeFile(backupUri, content);
    return backupUri;
  }

  /**
   * Restores env.py from backup
   */
  static async restoreFromBackup(
    envPyUri: vscode.Uri,
    backupUri: vscode.Uri,
  ): Promise<void> {
    const content = await vscode.workspace.fs.readFile(backupUri);
    await vscode.workspace.fs.writeFile(envPyUri, content);
    await vscode.workspace.fs.delete(backupUri);
  }

  /**
   * Generates the include_object function code based on filters
   */
  static generateIncludeObjectFunction(filters: EnvPyFilter[]): string {
    if (filters.length === 0) {
      return "";
    }

    const filterChecks: string[] = [];

    for (const filter of filters) {
      const mode = filter.mode === "include" ? "" : "not ";

      switch (filter.type) {
        case "schema":
          filterChecks.push(
            `    if object.schema == ${JSON.stringify(filter.pattern)}: return ${mode}True`,
          );
          break;
        case "table":
          filterChecks.push(
            `    if name == ${JSON.stringify(filter.pattern)} and type_ == "table": return ${mode}True`,
          );
          break;
        case "glob":
          filterChecks.push(
            `    if fnmatch.fnmatch(name, ${JSON.stringify(filter.pattern)}): return ${mode}True`,
          );
          break;
        case "regex":
          filterChecks.push(
            `    if re.match(${JSON.stringify(filter.pattern)}, name): return ${mode}True`,
          );
          break;
      }
    }

    const needsFnmatch = filters.some((f) => f.type === "glob");
    const needsRe = filters.some((f) => f.type === "regex");
    const imports: string[] = [];
    if (needsFnmatch) {
      imports.push("import fnmatch");
    }
    if (needsRe) {
      imports.push("import re");
    }

    const importsStr = imports.length > 0 ? imports.join("\n") + "\n\n" : "";

    return `${importsStr}def include_object(object, name, type_, reflected, compare_to):
    """
    Filter objects during autogenerate based on configured rules.
    Generated by vscode-alembic extension.
    """
${filterChecks.join("\n")}
    return True

`;
  }

  /**
   * Patches env.py with the provided configuration
   */
  static async patchEnvPy(
    envPyUri: vscode.Uri,
    config: EnvPyConfig,
  ): Promise<void> {
    const content = (await vscode.workspace.fs.readFile(envPyUri)).toString();
    const lines = content.split(/\r?\n/);

    // Remove any existing generated include_object function
    const cleanedLines = this.removeGeneratedFunctions(lines);

    // Find context.configure() calls and patch them
    const patchedLines = this.patchContextConfigure(
      cleanedLines,
      config.includeSchemas,
      config.filters.length > 0,
    );

    // Add include_object function if filters are defined
    let finalContent = patchedLines.join("\n");
    if (config.filters.length > 0) {
      const includeObjectFunc = this.generateIncludeObjectFunction(
        config.filters,
      );
      // Insert before the first def run_migrations_ function
      const runMigrationsIndex = patchedLines.findIndex((line) =>
        /^def\s+run_migrations_/.test(line),
      );
      if (runMigrationsIndex > 0) {
        patchedLines.splice(runMigrationsIndex, 0, includeObjectFunc);
        finalContent = patchedLines.join("\n");
      } else {
        // If no run_migrations_ found, append at the end
        finalContent = includeObjectFunc + finalContent;
      }
    }

    await vscode.workspace.fs.writeFile(
      envPyUri,
      Buffer.from(finalContent, "utf8"),
    );
  }

  /**
   * Removes previously generated include_object functions
   */
  private static removeGeneratedFunctions(lines: string[]): string[] {
    const result: string[] = [];
    let inGeneratedFunction = false;
    let skipImports = false;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // Check if we're starting a generated function
      if (
        line.includes("def include_object(") &&
        i + 3 < lines.length &&
        lines
          .slice(i, i + 5)
          .some((l) => l.includes("Generated by vscode-alembic extension"))
      ) {
        inGeneratedFunction = true;
        skipImports = true;
        continue;
      }

      // Skip generated imports (fnmatch, re) that were added before the function
      if (
        skipImports &&
        (line.trim() === "import fnmatch" || line.trim() === "import re")
      ) {
        continue;
      }

      // Exit generated function when we hit a non-indented line or another def
      if (inGeneratedFunction) {
        if (line && !line.startsWith(" ") && !line.startsWith("\t")) {
          inGeneratedFunction = false;
          skipImports = false;
        } else {
          continue;
        }
      }

      skipImports = false;
      result.push(line);
    }

    return result;
  }

  /**
   * Patches context.configure() calls to add include_schemas and include_object
   */
  private static patchContextConfigure(
    lines: string[],
    includeSchemas: boolean,
    hasFilters: boolean,
  ): string[] {
    const result: string[] = [];
    let inContextConfigure = false;
    let configureIndent = 0;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // Detect context.configure( call
      if (/context\.configure\(/.test(line)) {
        inContextConfigure = true;
        const match = line.match(/^(\s*)/);
        configureIndent = match ? match[1].length : 0;
        result.push(line);
        continue;
      }

      // If we're in context.configure, look for the closing paren
      if (inContextConfigure) {
        // Check if this line closes the call
        if (/^\s*\)/.test(line) || line.trim().endsWith(")")) {
          // Add our parameters before the closing paren
          const indent = " ".repeat(configureIndent + 4);

          // Remove existing include_schemas and include_object if present
          const configLines = result.slice(
            result.findIndex((l) => /context\.configure\(/.test(l)) + 1,
          );
          const filteredResult = result.slice(
            0,
            result.findIndex((l) => /context\.configure\(/.test(l)) + 1,
          );
          for (const cLine of configLines) {
            if (
              !cLine.includes("include_schemas=") &&
              !cLine.includes("include_object=")
            ) {
              filteredResult.push(cLine);
            }
          }
          result.length = 0;
          result.push(...filteredResult);

          // Add new parameters
          if (includeSchemas) {
            result.push(`${indent}include_schemas=True,`);
          }
          if (hasFilters) {
            result.push(`${indent}include_object=include_object,`);
          }

          result.push(line);
          inContextConfigure = false;
          continue;
        }

        // Skip existing include_schemas and include_object lines
        if (
          line.includes("include_schemas=") ||
          line.includes("include_object=")
        ) {
          continue;
        }
      }

      result.push(line);
    }

    return result;
  }

  /**
   * Validates env.py structure
   */
  static async validateEnvPy(envPyUri: vscode.Uri): Promise<boolean> {
    try {
      const content = (await vscode.workspace.fs.readFile(envPyUri)).toString();
      return (
        content.includes("context.configure") &&
        content.includes("def run_migrations_")
      );
    } catch {
      return false;
    }
  }
}
