#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${TEST_PROJECT_DIR:-/tmp/test-alembic-project}"
PYTHON_BIN="${PYTHON:-python3}"
DB_PORT="${TEST_DB_PORT:-55432}"
DB_NAME="${TEST_DB_NAME:-alembic_test}"
DB_USER="${TEST_DB_USER:-alembic}"
DB_PASSWORD="${TEST_DB_PASSWORD:-alembic}"
VENV_DIR="$PROJECT_DIR/venv"
ALEMBIC_BIN="$VENV_DIR/bin/alembic"
DB_URL="postgresql+psycopg2://$DB_USER:$DB_PASSWORD@localhost:$DB_PORT/$DB_NAME"

mkdir -p "$PROJECT_DIR"

if [ ! -d "$VENV_DIR" ]; then
  "$PYTHON_BIN" -m venv "$VENV_DIR"
fi

"$VENV_DIR/bin/pip" install --upgrade pip
"$VENV_DIR/bin/pip" install alembic sqlalchemy psycopg2-binary

cat > "$PROJECT_DIR/docker-compose.yml" <<YAML
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 20
YAML

if [ ! -f "$PROJECT_DIR/alembic.ini" ]; then
  (cd "$PROJECT_DIR" && "$ALEMBIC_BIN" init alembic)
fi

if grep -q '^sqlalchemy.url' "$PROJECT_DIR/alembic.ini"; then
  sed -i.bak -E "s|^sqlalchemy\\.url[[:space:]]*=.*$|sqlalchemy.url = ${DB_URL}|" "$PROJECT_DIR/alembic.ini"
  rm -f "$PROJECT_DIR/alembic.ini.bak"
else
  printf '\nsqlalchemy.url = %s\n' "$DB_URL" >> "$PROJECT_DIR/alembic.ini"
fi

cat > "$PROJECT_DIR/models.py" <<'PY'
from sqlalchemy import String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
PY

cat > "$PROJECT_DIR/alembic/env.py" <<'PY'
from logging.config import fileConfig
from pathlib import Path
import sys

from sqlalchemy import engine_from_config, pool

from alembic import context

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from models import Base  # noqa: E402

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
PY

cat > "$PROJECT_DIR/README.md" <<MD
# Alembic Extension Test Project

This project is generated by the vscode-alembic repository Makefile.

## Database

\`\`\`bash
docker compose up -d
\`\`\`

Connection URL:

\`\`\`
${DB_URL}
\`\`\`

## Alembic

\`\`\`bash
source venv/bin/activate
alembic history
alembic revision --autogenerate -m "create users table"
alembic upgrade head
alembic current
\`\`\`
MD

echo "Test project is ready: $PROJECT_DIR"
echo "Database URL: $DB_URL"
echo "Python interpreter: $VENV_DIR/bin/python"
